# Generated by Django 5.0.14 on 2026-07-12 10:03

import apps.chamas.models.chama
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('invite_code', models.CharField(default=apps.chamas.models.chama.generate_invite_code, max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_chamas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chamas',
                'ordering': ['-created_at'],
            },
        ),
    ]
