# Generated by Django 5.0.14 on 2026-07-12 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('loan_applied', 'Loan Applied'), ('loan_approved', 'Loan Approved'), ('loan_rejected', 'Loan Rejected'), ('contribution_recorded', 'Contribution Recorded'), ('repayment_recorded', 'Repayment Recorded'), ('committee_vote_completed', 'Committee Vote Completed')], max_length=50)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('sms', 'SMS'), ('email', 'Email')], default='in_app', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='notificatio_user_id_5cf777_idx')],
            },
        ),
    ]
