# Generated by Django 5.0.14 on 2026-07-12 10:56

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('due_day', models.PositiveSmallIntegerField()),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_cycles', to='chamas.chama')),
            ],
            options={
                'db_table': 'contribution_cycles',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['chama', 'status'], name='contributio_chama_i_e46896_idx'), models.Index(fields=['chama', 'start_date'], name='contributio_chama_i_57ce7b_idx')],
            },
        ),
    ]
