# Generated by Django 5.0.14 on 2026-07-12 11:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank')], max_length=20)),
                ('reference', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField()),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='contributions.contributioncycle')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contributions',
                'ordering': ['-recorded_at', '-created_at'],
                'indexes': [models.Index(fields=['cycle', 'member'], name='contributio_cycle_i_6dea7d_idx'), models.Index(fields=['member', 'recorded_at'], name='contributio_member__e5bf7a_idx'), models.Index(fields=['recorded_at'], name='contributio_recorde_bca3df_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='unique_contribution_idempotency_key'),
        ),
    ]
