# Generated by Django 5.0.14 on 2026-07-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_contribution_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contribution',
            name='unique_contribution_idempotency_key',
        ),
        migrations.AlterField(
            model_name='contribution',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
