# Generated by Django 5.0.14 on 2026-07-12 12:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chamas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField()),
                ('risk_level', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('high_risk', 'High Risk')], max_length=20)),
                ('breakdown', models.JSONField(default=dict)),
                ('weights', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField()),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_scores', to='chamas.chama')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_scores', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_credit_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_scores',
                'ordering': ['-calculated_at', '-created_at'],
                'indexes': [models.Index(fields=['chama', 'member', 'calculated_at'], name='credit_scor_chama_i_457ddd_idx')],
            },
        ),
    ]
